language: ruby

cache: bundler

sudo: false

rvm:
  - ruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_3.2.gemfile

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_3.2.gemfile
  allow_failures:
    - rvm: ruby-head