language: ruby
cache: bundler
sudo: false
rvm:
  - ruby-head
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
  - 2.2.10
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_3.2.gemfile
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_3.2.gemfile
  allow_failures:
    - rvm: ruby-head