language: ruby
cache: bundler
sudo: false
rvm:
  - ruby-head
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - 2.2.10
gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_3.2.gemfile
before_install:
  # Rails 4.x requires Bundler version < 2.0.
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do yes | gem install bundler -v '< 2'
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_3.2.gemfile
  allow_failures:
    - rvm: ruby-head
